name: ddr_md
description: "DDR Markdown"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/jackets-lowres/
    - assets/jackets/
    - assets/song-data/
  fonts:
    - family: Handel
      fonts: 
        - asset: fonts/handel_gothic.ttf
  uses-material-design: true
