/// Name: Steps model + loader
/// Description: Per-difficulty note streams for the scrolling chart renderer
/// (and, later, the dancing bot). Unlike the song summary in [SongInfo], step
/// data is large and per-difficulty, so it is NOT bundled into the master song
/// list loaded at startup — it lives in assets/steps/<name>.json and is read
/// lazily, only when a chart view is opened, then discarded on close.
library;

import 'dart:convert';

import 'package:ddr_md/components/song_json.dart';
import 'package:ddr_md/models/parity.dart';
import 'package:flutter/services.dart';

/// Note type codes, matching the pipeline's SimfileParser step encoding.
enum StepType { tap, hold, roll, mine }

StepType _stepTypeFrom(int t) {
  switch (t) {
    case 1:
      return StepType.hold;
    case 2:
      return StepType.roll;
    case 3:
      return StepType.mine;
    default:
      return StepType.tap;
  }
}

/// A single arrow (or mine). Holds/rolls carry the beat+second of their tail
/// so the renderer can draw the sustain bar; taps/mines leave those null.
///
/// Foot (L/R) parity is NOT stored here: it is a derived, best-effort guide
/// computed on the fly by [FootAssigner] when a chart is opened, so it can be
/// tuned freely without regenerating every steps asset. See [FootAssigner].
class StepNote {
  final double beat;
  final double second;
  final int col;
  final StepType type;
  final double? endBeat;
  final double? endSecond;

  const StepNote({
    required this.beat,
    required this.second,
    required this.col,
    required this.type,
    this.endBeat,
    this.endSecond,
  });

  bool get isHold => type == StepType.hold || type == StepType.roll;

  factory StepNote.fromJson(Map<String, dynamic> json) => StepNote(
        beat: (json["b"] as num).toDouble(),
        second: (json["s"] as num).toDouble(),
        col: json["c"] as int,
        type: _stepTypeFrom(json["t"] as int),
        endBeat: (json["e"] as num?)?.toDouble(),
        endSecond: (json["es"] as num?)?.toDouble(),
      );
}

/// Which foot a step is danced with.
enum Foot { left, right }

/// One difficulty's ordered note stream.
class ChartSteps {
  final List<StepNote> notes;

  const ChartSteps({required this.notes});

  factory ChartSteps.fromJson(Map<String, dynamic> json) => ChartSteps(
        notes: List<StepNote>.from(
          (json["notes"] as List<dynamic>? ?? [])
              .map((x) => StepNote.fromJson(x as Map<String, dynamic>)),
        ),
      );
}

/// All difficulties of one song, keyed sp/dp -> difficulty name (beginner..
/// challenge), matching [Difficulty.availableTypes].
class SongSteps {
  final String name;
  final Map<String, ChartSteps> singles;
  final Map<String, ChartSteps> doubles;

  const SongSteps({
    required this.name,
    required this.singles,
    required this.doubles,
  });

  static Map<String, ChartSteps> _parseCharts(dynamic charts) =>
      (charts as Map<String, dynamic>? ?? {}).map(
        (diff, v) =>
            MapEntry(diff, ChartSteps.fromJson(v as Map<String, dynamic>)),
      );

  factory SongSteps.fromJson(Map<String, dynamic> json) {
    final charts = json["charts"] as Map<String, dynamic>? ?? {};
    return SongSteps(
      name: json["name"] as String? ?? "",
      singles: _parseCharts(charts["sp"]),
      doubles: _parseCharts(charts["dp"]),
    );
  }

  /// The note stream for [mode]'s [difficultyKey] (e.g. "challenge"), or null
  /// when that difficulty has no bundled steps.
  ChartSteps? chartFor(Modes mode, String difficultyKey) =>
      (mode == Modes.singles ? singles : doubles)[difficultyKey];
}

/// Loads a song's step file lazily from the asset bundle. Returns null when the
/// song has no bundled steps (e.g. not yet regenerated by the pipeline), so the
/// caller can hide the chart renderer gracefully.
class StepsLoader {
  static Future<SongSteps?> load(String songName) async {
    try {
      // `cache: false`: the decoded string is large and only needed to build
      // the model once; keeping it pinned in rootBundle's cache would hold the
      // whole note stream in memory after the view closes.
      final raw = await rootBundle.loadString(
        "assets/steps/$songName.json",
        cache: false,
      );
      return SongSteps.fromJson(json.decode(raw) as Map<String, dynamic>);
    } catch (_) {
      return null;
    }
  }
}

/// Best-effort L/R foot parity for a note stream, computed client-side so the
/// engine can be tuned without regenerating steps assets.
///
/// This delegates to the cost-minimising parity engine in [assignParity]
/// (ported from SMEditor): it models the pad as physical geometry, scores every
/// legal foot placement per row with a weighted cost model, and picks the
/// minimum-cost path through the whole chart. Crossovers and footswitches
/// emerge correctly because they read the notes that follow — something the
/// earlier greedy per-note solver structurally could not do.
class FootAssigner {
  /// Assigns a foot to every non-mine note, returning a map keyed by the note
  /// instance. Mines are skipped (never danced with a foot).
  static Map<StepNote, Foot> assign(List<StepNote> notes, Modes mode) {
    final parity = assignParity(notes, mode);
    return parity.map(
      (note, foot) =>
          MapEntry(note, foot == ParityFoot.left ? Foot.left : Foot.right),
    );
  }
}
