#!/usr/bin/env bash
#
# Build Tesseract + Leptonica + libjpeg + libpng as static libraries for iOS arm64.
# Outputs .a files + headers into native_opencv/ios/libs/
#
# Usage:  ./scripts/build_tesseract_ios.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_BASE="$REPO_ROOT/native_opencv/android/src/main/cpp"
CMAKE_DIR="$SCRIPT_DIR/ios_tesseract_cmake"
OUTPUT_DIR="$REPO_ROOT/native_opencv/ios/libs"
BUILD_DIR="$REPO_ROOT/build/ios_tesseract"

IOS_DEPLOYMENT_TARGET="13.0"

echo "=== Building Tesseract static libs for iOS arm64 ==="
echo "Source dir:  $SRC_BASE"
echo "CMake dir:   $CMAKE_DIR"
echo "Build dir:   $BUILD_DIR"
echo "Output dir:  $OUTPUT_DIR"

# ── Clean previous build ────────────────────────────────────────────
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

# ── Configure with CMake ────────────────────────────────────────────
cmake -S "$CMAKE_DIR" -B "$BUILD_DIR" \
    -G "Unix Makefiles" \
    -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_ARCHITECTURES=arm64 \
    -DCMAKE_OSX_DEPLOYMENT_TARGET="$IOS_DEPLOYMENT_TARGET" \
    -DCMAKE_OSX_SYSROOT=iphoneos \
    -DCMAKE_C_COMPILER_WORKS=1 \
    -DCMAKE_CXX_COMPILER_WORKS=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DSRC_BASE="$SRC_BASE"

# ── Build ───────────────────────────────────────────────────────────
cmake --build "$BUILD_DIR" -j "$(sysctl -n hw.ncpu)"

# ── Collect outputs ─────────────────────────────────────────────────
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR/include/tesseract" "$OUTPUT_DIR/include/leptonica"

# Copy static libraries
cp "$BUILD_DIR/libjpeg.a"     "$OUTPUT_DIR/"
cp "$BUILD_DIR/libpngx.a"    "$OUTPUT_DIR/"
cp "$BUILD_DIR/libleptonica.a" "$OUTPUT_DIR/"
cp "$BUILD_DIR/libtesseract.a" "$OUTPUT_DIR/"

# Copy public headers needed by our code
# Tesseract public API
cp "$SRC_BASE/tesseract/src/include/tesseract/"*.h           "$OUTPUT_DIR/include/tesseract/" 2>/dev/null || true
# config_auto.h is generated by configure_file into the source tree
cp "$SRC_BASE/tesseract/src/src/api/config_auto.h"          "$OUTPUT_DIR/include/tesseract/" 2>/dev/null || true

# Leptonica public headers (allheaders.h and friends)
cp "$SRC_BASE/leptonica/src/src/allheaders.h"  "$OUTPUT_DIR/include/leptonica/"
cp "$SRC_BASE/leptonica/src/src/"*.h           "$OUTPUT_DIR/include/leptonica/" 2>/dev/null || true

echo ""
echo "=== Build complete ==="
echo "Static libraries:"
ls -lh "$OUTPUT_DIR/"*.a
echo ""
echo "Headers in: $OUTPUT_DIR/include/"
echo ""
echo "Next: run 'cd ios && pod install'"
